"""Sprint E7 Task 5: the signal reports are traceable to stored artifacts.

The reports are generated by `sprints/E7/write_reports.py`, which reads only
artifacts; this test pins the outcome: every number in every report comes
from the stored frames and the stored gate, and every signal has a verdict.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pandas as pd
import pytest

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "alpha"
GATE = ROOT / "sprints" / "E7" / "RG_SIGNAL.json"
RESULTS = ROOT / "sprints" / "E7" / "RESULTS.json"

SIGNALS = (
    "momentum_12_1",
    "short_term_reversal",
    "idio_momentum",
    "low_residual_volatility",
    "short_interest",
    "post_earnings_drift",
)


@pytest.fixture(scope="module")
def stored_numbers() -> list[float]:
    """Every number the reports can cite, from the stored artifacts."""
    gate = json.loads(GATE.read_text())
    results = json.loads(RESULTS.read_text())
    texts = [
        json.dumps(gate),
        json.dumps(results),
        pd.read_parquet(DATA / "summary.parquet")
        .select_dtypes(include="number")
        .to_string(),
    ]
    for name in SIGNALS:
        for stem in ("ic", "neutral_ic", "regime_ic", "quantiles"):
            frame = pd.read_parquet(DATA / name / f"{stem}.parquet")
            texts.append(frame.select_dtypes(include="number").to_string())
    return [
        float(match)
        for text in texts
        for match in re.findall(r"-?\d+\.\d+(?:e-?\d+)?", text)
    ]


@pytest.mark.integration
def test_every_signal_has_a_report_with_a_verdict() -> None:
    for name in SIGNALS:
        path = ROOT / "docs" / "research" / f"E7_signal_{name}.md"
        assert path.exists(), name
        text = " ".join(path.read_text().split())
        verdict = json.loads(GATE.read_text())[name]["verdict"]
        assert f"Verdict against the RG-Signal checklist: **{verdict}**" in text


@pytest.mark.integration
def test_every_number_in_the_reports_is_traceable(
    stored_numbers: list[float],
) -> None:
    offenders: list[tuple[str, str]] = []
    for name in SIGNALS:
        text = " ".join(
            (ROOT / "docs" / "research" / f"E7_signal_{name}.md").read_text().split()
        )
        for match in re.findall(r"-?\d+\.\d+", text):
            value = abs(float(match))
            digits = len(match.split(".")[1])
            tolerance = 0.5 * 10 ** (-digits)
            if not any(abs(abs(v) - value) <= tolerance for v in stored_numbers):
                offenders.append((name, match))
    assert offenders == [], f"numbers not traceable: {offenders}"


@pytest.mark.integration
def test_the_gate_has_seven_answers_per_signal() -> None:
    gate = json.loads(GATE.read_text())
    for name in SIGNALS:
        assert len(gate[name]["answers"]) == 7, name
        assert gate[name]["deciding_number"]["neutral_ic_oos_t"] is not None


@pytest.mark.integration
def test_the_ledger_labels_the_null_signals() -> None:
    ledger = (ROOT / "docs" / "multiple_testing_ledger.md").read_text()
    gate = json.loads(GATE.read_text())
    for name, block in gate.items():
        if block["verdict"] == "NULL":
            assert f"| {name} |" in ledger
            assert "NULL" in ledger
