// The bundled ticker-to-GICS map.
//
// The snapshot has no sector per name, so the page carries one: a JSON file
// generated by `scripts/make_sector_map.py` from `data/processed/sectors.parquet`
// (the ticker-to-GICS table the risk model itself uses) and the dated
// `data/raw/spy_holdings/` archive (the current membership, which carries no
// sector of its own). `tests/test_web_sector_map.py` regenerates it and asserts
// the committed bytes, so it cannot go stale quietly.
//
// A name the map does not carry is rendered as Unmapped rather than guessed at.
// Three of the current index's tickers have no sector row, and a new listing has
// none until the vendor's table catches up: saying so is the honest reading.

import raw from "./sector_map.json";

export const UNMAPPED = "Unmapped";

export interface SectorMapSource {
  sectors: string;
  sectors_as_of: string | null;
  holdings: string;
  holdings_as_of: string | null;
  codes: string;
}

interface SectorMapFile {
  source: SectorMapSource;
  sectors: Record<string, string>;
  tickers: Record<string, number>;
}

const file = raw as SectorMapFile;

/** The GICS code for a ticker, or null when the map does not carry it. */
export function sectorCodeFor(ticker: string): number | null {
  const code = file.tickers[ticker.trim().toUpperCase()];
  return code === undefined ? null : code;
}

/** The sector's own name, or "Unmapped". */
export function sectorNameFor(ticker: string): string {
  return sectorLabel(sectorCodeFor(ticker));
}

/** A code's name, or "Unmapped" for a code the model does not estimate. */
export function sectorLabel(code: number | null): string {
  if (code === null) return UNMAPPED;
  return file.sectors[String(code)] ?? UNMAPPED;
}

/** Where the map came from and when, so the page can say what it is showing. */
export const sectorMapSource: SectorMapSource = file.source;

/** Every code the map knows, in code order. */
export const sectorCodes: number[] = Object.keys(file.sectors)
  .map(Number)
  .sort((a, b) => a - b);
